### PR TITLE
Refactoring Publication models + XmlParser rewrite with namespaces handling

### LINKED ISSUE #35: Implement subtitle
It was added some time ago to the model, implemented on iOS.

### LINKED ISSUE #36: Double check tweaks made since the beginning of the project
Added subtitle
Added duration
Added numberOfPages
Extended list of contributors
spine became readingOrder
direction became readingProgression
sort-as became sortAs
belongs-to became belongsTo

### LINKED ISSUE #38: Extensibility

### LINKED ISSUE #86: Using kotlin data classes
I am writing unit tests for my new PackageDocumentParser and once again I have some issues with Shared module coding style because Publication content objects don't implement an equals method.
If that's ok for you, I suggest I refactor Publication model into safer and more idiomatic Kotlin (data classes with immutable members).

### LINKED ISSUE #87: MultilanguageString
I can't fully understand the intent behind MultilanguageString objects, used for example for titles. In the Readium manifest specification, a title is either a String, or a map from language to title, not both.
In the [Epub Metadata Parsing Guide](https://readium.org/architecture/streamer/parser/metadata.html) one can't find any mention of "singleString" either.
Since, content from <dc:title> is put into the map after determining the tag language, what is singleString for? Should it contain a copy of the title in the default language for metadata, computed as specified in the Epub Metadata Parsing Guide?

### PR DESCRIPTION
**Pull request by mickael-menu**
Refactoring of the Publication models to align with Swift and add missing features/models.

Fixes #87, Fixes #86, Fixes #38, Fixes #35, Fixes #36, Fixes https://github.com/readium/architecture/issues/113

- Move all the related models to the [`publication` package](https://github.com/readium/r2-shared-kotlin/tree/fixes/publication-models/r2-shared/src/main/java/org/readium/r2/shared/publication).
  - There's one additional sub-package per module/extension (eg. EPUB, Presentation Hints).
- All Publication models are now Kotlin data classes to take advantage of equality and copy (used in unit tests).
  - Properties are now immutable to improve the safety of the model.
  - A few properties in `Publication` are still mutable because R2's implementation relies on it (e.g. adding the `self` link).
- Add extensibility through JSON maps in `Publication`, `Metadata` and `Properties`.
  - Using Kotlin extensions we can map the internal JSON objects to higher structures seamlessly. [Here's an example with EPUB's `Properties` extensions](https://github.com/readium/r2-shared-kotlin/blob/fixes/publication-models/r2-shared/src/main/java/org/readium/r2/shared/publication/epub/Properties.kt).
  - Any third-party app can add custom Kotlin extensions for their own properties.
- Add the [Presentation Hints](https://github.com/readium/r2-shared-kotlin/tree/fixes/publication-models/r2-shared/src/main/java/org/readium/r2/shared/publication/presentation) module.
- Add a [`WarningLogger` interface](https://github.com/readium/r2-shared-kotlin/blob/fixes/publication-models/r2-shared/src/main/java/org/readium/r2/shared/util/logging/WarningLogger.kt) to forward issues while building a `Publication` to the test-app.
  - The rationale is that sometimes we want to ignore non-fatal errors while parsing a RWPM or an EPUB package to still return the parsed `Publication`. Having a way to observe internal warnings can be of interest for the test-app/debugging.
  - This is related to this Swift issue: https://github.com/readium/r2-shared-swift/issues/60
  - Note 1: For now, this is internal, because it might change with the specification of the Streamer API.
  - Note 2: I think this strategy should be expanded for other internal logs that we might want to emit from R2 projects. This way the third-party app will have the control on what to do with these logs. 
- [Add a unit test suite for the models JSON parsing/serializing](https://github.com/readium/r2-shared-kotlin/tree/fixes/publication-models/r2-shared/src/test/java/org/readium/r2/shared)
- Use `Parcelable` instead of `Serializable` to share `Publication` through `Intent`.
- Rename types and enums to follow the Google Android Style coding convention regarding case.

A few things are left to be refactored later:
- `Publication.TYPE` is mixing up a few things together, but the test-app is still relying a lot on it. I opened an issue for that: https://github.com/readium/architecture/issues/112
- `Publication.internalData` should be removed, but is used right now in the streamer to send the rootFile. I think that this information is already available in the `Container` though.
- I didn't touch the `MediaOverlays` models since it is not yet fully specified and a WIP (same thing on Swift).

This issue still needs to be resolved before merging this refactoring: https://github.com/readium/webpub-manifest/issues/42

---

This PR now also contains this one from @qnga : #85

> In a robust and conformant implementation, attributes and elements should not be identified just by their name or usual prefixes. Default namespace can differ from one XML file to another and can change along the way. Prefixes are completely arbitrary and authors are allowed to use anything that comes to their mind.

## Migration Guide for the Client Apps

1. Replace the following imports everywhere:
   - `org.readium.r2.shared.Publication` by `org.readium.r2.shared.publication.Publication`
   - `org.readium.r2.shared.Link` by `org.readium.r2.shared.publication.Link`
   - `org.readium.r2.shared.Locator` by `org.readium.r2.shared.publication.Locator`

2. Automatically import unresolved references with Alt-Enter > Import.
   - This will be needed for `publication.images`, `publication.landmarks` and `publication.pageList`.

3. In `R2OutlineActivity.kt`, use `List<Link>` instead of `MutableList<Link>` in
```kotlin
val contents: MutableList<Link> = when {
```

4. In `R2SyntheticPageList.kt`, use `List<Link>` instead of `MutableList<Link>` in
```kotlin
class R2SyntheticPageList(private val positionsDB: PositionsDatabase, private val bookID: Long, private val publicationIdentifier: String) : AsyncTask<Triple<String, String, MutableList<Link>>, String, MutableList<Position>>() {
```
5. Replace everywhere:
  - `intent.getSerializableExtra("publication")` by `intent.getParcelableExtra("publication")`
  - `intent.getSerializableExtra("locator")` by `intent.getParcelableExtra("locator")`
  - `SearchLocator` by `Locator` (and remove implementation of `SearchLocator`)

6. Upgrade the implementation of `Bookmark`, `Highlight`.

7. In `EpubActivity.kt`, replace
```kotlin
val highlightLocations = highlight.locator.locations?.apply {
    progression = currentLocation?.locations?.progression
    position = currentPage
} ?: Locations()
```
by
```kotlin
val highlightLocations = highlight.locator.locations.copy(
    progression = currentLocation?.locations?.progression,
    position = currentPage?.toInt()
)
```

8. Remove `currentLocation` overrides in `EpubActivity`, `ComicActivity` and `AudiobookActivity`.

9. [Fix loading the CSS styles](https://github.com/readium/r2-testapp-kotlin/commit/5a76a9724275bfc2df49a26cb535c08aa2409088)

10. (Optional) Follow the deprecation warnings and apply the suggested fixes.

### CODE REVIEW

**Comment by mickael-menu** [comment]
@qnga There's one thing that you need to keep in mind for the EPUB parser: when extracting hrefs from XML, they need to be URL decoded (this is used in encryption.xml, or when creating `Link`, for example).

[Some checks used to be done](https://github.com/readium/r2-shared-kotlin/blob/c6208fa0db42fffdf88aeec8700447b9575b2f70/r2-shared/src/main/java/org/readium/r2/shared/Publication.kt#L182) directly in `Publication` but this was very fragile because you needed to use these APIs for comparison. I removed this and instead `Link.href` must be "normalized" in the EPUB parser itself. This is done like that in the Swift parser: https://github.com/readium/r2-streamer-swift/commit/f1471e43008e7c4450e8b0fdc12875b7892b6455

If you do it in the `encryption.xml` parser as well, this will fix this issue: https://github.com/readium/r2-lcp-kotlin/issues/50

**Comment by mickael-menu** [comment]
This PR now also contains this one from @qnga : https://github.com/readium/r2-shared-kotlin/pull/85

> In a robust and conformant implementation, attributes and elements should not be identified just by their name or usual prefixes. Default namespace can differ from one XML file to another and can change along the way. Prefixes are completely arbitrary and authors are allowed to use anything that comes to their mind.

**Comment by qnga** [comment]
> @qnga There's one thing that you need to keep in mind for the EPUB parser: when extracting hrefs from XML, they need to be URL decoded (this is used in encryption.xml, or when creating Link, for example).

To keep track, we have decided to decode URLs in PublicationParser.normalize, always used to resolve relative paths.

**Comment by mickael-menu** [comment]
I added a migration guide for the client apps in the PR's description.

**Comment by mickael-menu** [comment]
I intend to merge this next Monday.

**Comment by mickael-menu** [comment]
I put `WarningLogger` as internal until the Streamer API is specified, since it might change to fit the needs of the streamer.

**Pull request merged**
